Exercícios 4-9/sitepr/sitepr/sitepr/urls.py
from django.urls import include, path
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
 path('votacao/', include('votacao.urls')),
 path('admin/', admin.site.urls),
]

if settings.DEBUG:
 urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Exercícios 4-9/sitepr/sitepr/votacao/urls.py
from django.urls import include, path
from . import views
from django.utils import timezone
import datetime
# (. significa que importa views da mesma directoria)

app_name = 'votacao'

urlpatterns = [ path("", views.index, name="index"),
                path("<int:questao_id>", views.detalhe, name="detalhe"),
                path("<int:questao_id>/resultados", views.resultados, name="resultados"),
                path("<int:questao_id>/voto", views.voto, name="voto"),
                path("view_questao_otimizada", views.view_questao_otimizada, name="view_questao_otimizada"),
                path("registar", views.registar, name="registar"),
                path("logoutview", views.logoutview, name="logoutview"),
                path("iniciarsessao", views.iniciarsessao, name="iniciarsessao"),
                path("perfil", views.perfil, name="perfil"),
                path("<int:questao_id>/view_opcao_otimizada", views.view_opcao_otimizada, name="view_opcao_otimizada"),
                path("<int:questao_id>/apagarquestao", views.apagarquestao, name="apagarquestao"),
                path("<int:questao_id>/apagaropcao", views.apagaropcao, name="apagaropcao"),
                path("fazer_upload", views.fazer_upload, name="fazer_upload"),
                ]

Exercícios 4-9/sitepr/sitepr/votacao/models.py
from django.db import models
from django.utils import timezone
import datetime
from django.contrib.auth import authenticate, login
from django.contrib.auth.models import User

class Questao(models.Model):
 questao_texto = models.CharField(max_length=200)
 pub_data = models.DateTimeField('data de publicacao')

 def __str__(self):
  return self.questao_texto


 def foi_publicada_recentemente(self):
  return self.pub_data >= timezone.now() - datetime.timedelta(days=1)

class Opcao(models.Model):
 questao = models.ForeignKey(Questao, on_delete=models.CASCADE)
 opcao_texto = models.CharField(max_length=200)
 votos = models.IntegerField(default=0)

 def __str__(self):
  return self.opcao_texto

class Aluno(models.Model):
 user = models.OneToOneField(User, on_delete=models.CASCADE)
 course = models.CharField(max_length=50)

class Foto(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    foto_url = models.URLField(max_length=100)

Exercícios 4-9/sitepr/sitepr/votacao/views.py
from django.core.files.storage import FileSystemStorage
from django.shortcuts import render
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, render
from django.http import Http404, HttpResponse, HttpResponseRedirect
from django.template import loader
from django.urls import reverse, reverse_lazy
from django.utils import timezone
import datetime
from django.contrib.auth import authenticate, login
from django.contrib.auth.models import User
from django.utils.datastructures import MultiValueDictKeyError
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth import logout
from django.shortcuts import redirect
from django.contrib.auth.decorators import login_required, permission_required

from .models import Questao, Opcao, Aluno, Foto

def index(request):
    try:
        latest_question_list = Questao.objects.all()
        uploaded_file_url = request.user.foto.foto_url
        return render(request, 'votacao/index.html', {'latest_question_list': latest_question_list, 'uploaded_file_url': uploaded_file_url})
    except ObjectDoesNotExist:
        latest_question_list = Questao.objects.all()
        return render(request, 'votacao/index.html', {'latest_question_list': latest_question_list})

def detalhe(request, questao_id):
    questao = get_object_or_404(Questao, pk=questao_id)
    return render(request, 'votacao/detalhe.html', {'questao': questao})

@login_required(login_url='/votacao/iniciarsessao')
def voto(request, questao_id):
    questao = get_object_or_404(Questao, pk=questao_id)
    try:
        opcao_seleccionada = questao.opcao_set.get(pk=request.POST['opcao'])
    except (KeyError, Opcao.DoesNotExist):
    # Apresenta de novo o form para votar
        return render(request, 'votacao/detalhe.html', {'questao': questao, 'error_message': "Não escolheu uma opção",})
    else:
        opcao_seleccionada.votos += 1
        opcao_seleccionada.save()
 # Retorne sempre HttpResponseRedirect depois de
 # tratar os dados POST de um form
 # pois isso impede os dados de serem tratados
 # repetidamente se o utilizador
 # voltar para a página web anterior.
        return HttpResponseRedirect(reverse('votacao:resultados', args=(questao.id,)))

def resultados(request, questao_id):
    questao = get_object_or_404(Questao, pk=questao_id)
    return render(request, 'votacao/resultados.html', {'questao': questao})

@permission_required('votacao.add_questao', login_url=reverse_lazy('votacao:iniciarsessao'))
def view_questao_otimizada(request):
    if request.method == 'POST':
        questao_texto = request.POST['questao']
        pub_data = timezone.now()
        q = Questao(questao_texto=questao_texto, pub_data=pub_data)
        q.save()
        return HttpResponseRedirect(reverse('votacao:index'))
    else:
        return render(request, 'votacao/criarquestao.html')

@permission_required('votacao.add_opcao', login_url=reverse_lazy('votacao:iniciarsessao'))
def view_opcao_otimizada(request, questao_id):
    if request.method == 'POST':
        questao = Questao.objects.get(pk=questao_id)
        questao.opcao_set.create(opcao_texto=request.POST['opcao'], votos=0)
        return HttpResponseRedirect(reverse('votacao:detalhe', args=(questao.id,)))
    else:
        questao = get_object_or_404(Questao, pk=questao_id)
        return render(request, 'votacao/novaopcao.html', {'questao': questao})

@permission_required('votacao.add_opcao', login_url=reverse_lazy('votacao:iniciarsessao'))
def apagarquestao(request, questao_id):
    questao = get_object_or_404(Questao, pk=questao_id)
    questao.delete()
    return HttpResponseRedirect(reverse('votacao:index'))

@permission_required('votacao.add_opcao', login_url=reverse_lazy('votacao:iniciarsessao'))
def apagaropcao(request, questao_id):
    questao = get_object_or_404(Questao, pk=questao_id)
    try:
        opcao_seleccionada = questao.opcao_set.get(pk=request.POST['opcao'])
    except (KeyError, Opcao.DoesNotExist):
        return render(request, 'votacao/detalhe.html', {'questao': questao, 'error_message': "Não escolheu uma opção",})
    else:
        opcao_seleccionada.delete()
        return HttpResponseRedirect(reverse('votacao:detalhe', args=(questao.id,)))

def registar(request):
    try:
        username = request.POST['username']
        password = request.POST['password']
        email = request.POST['email']
        course = request.POST['course']
        u = User.objects.create_user(username, password=password, email=email)
        a = Aluno(user=u, course=course)
        a.save()
        user = authenticate(username=username, password=password)
        return render(request, 'votacao/iniciarsessao.html')
    except MultiValueDictKeyError:
        return render(request, 'votacao/registar.html')

def iniciarsessao(request):
    try:
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)

        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse('votacao:index'))

        else:
            return render(request, 'votacao/registar.html')
    except MultiValueDictKeyError:
        return render(request, 'votacao/iniciarsessao.html')


def perfil(request):
    try:
        uploaded_file_url = request.user.foto.foto_url
        return render(request, 'votacao/perfil.html', {'uploaded_file_url': uploaded_file_url})
    except ObjectDoesNotExist:
        return render(request, 'votacao/perfil.html')


def logoutview(request):
    logout(request)
    return HttpResponseRedirect(reverse('votacao:index'))

@login_required(login_url='votacao/registar.html')
def fazer_upload(request):
    if request.method == 'POST' and request.FILES['myfile']:
        myfile = request.FILES['myfile']
        fs = FileSystemStorage()
        filename = fs.save(myfile.name, myfile)
        uploaded_file_url = fs.url(filename)
        u = request.user.user_id
        foto = Foto(user=u, foto_url=uploaded_file_url)
        foto.save()
        return render(request,'votacao/perfil.html', {'uploaded_file_url': uploaded_file_url})
    return render(request, 'votacao/perfil.html')

Exercícios 4-9/sitepr/sitepr/votacao/templates/votacao/criarquestao.html
{% extends "./secondbase.html" %}

{% block titulo %} Criar questão {% endblock %}

{% block body %}
    <h2>Texto da nova Questão:</h2>
    <form action="{% url 'votacao:view_questao_otimizada' %}" method="post">
        {% csrf_token %}
        <input type="text" name="questao" id="questao">
        <input type="submit" value="Gravar nova Questão">
        <br>
        <br>
    </form>
    <br>

{% endblock %}

Exercícios 4-9/sitepr/sitepr/votacao/templates/votacao/detalhe.html
{% extends "./secondbase.html" %}

{% block titulo %} Questão {% endblock %}

{% block body %}

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <h1>{{ questao.questao_texto }}</h1>
    {% if error_message %}
        <p><strong>{{ error_message }}</strong></p>
    {% endif %}
    <form id="form1" action="{% url 'votacao:voto' questao.id %}" method="post">
        {% csrf_token %}
        {% for opcao in questao.opcao_set.all %}
            <input type="radio" name="opcao" id="opcao{{ forloop.counter }}" value="{{ opcao.id }}" />
            <label for="opcao{{ forloop.counter }}">{{ opcao.opcao_texto }}</label>
            <div id="votos{{ forloop.counter }}" class="votos" style="display: none">
                {{ opcao.votos }} voto{{ opcao.votos|pluralize }}
            </div>
            <script>
                $(document).ready(function (){

                    $("#opcao{{ forloop.counter }}").click(function (){
                        $(".votos").slideUp(300);
                        $("#votos{{ forloop.counter }}").slideDown(300);
                    });
                });
            </script>
        <br>
        <br>
        {% endfor %}
        <br>
        {% if request.user.is_authenticated %}
            <input type="submit" value="Voto" />
        {% endif %}
        <br>
        <br>
    </form>
    <br>
    {% if request.user.is_authenticated and request.user.is_superuser %}

        <form action="{% url 'votacao:view_opcao_otimizada' questao.id %}" method="get">
            {% csrf_token %}
            <input type="submit" value="Criar nova Opção" />
        </form>
        <br>
        <br>
        <form action="{% url 'votacao:apagarquestao' questao.id %}" method="get">
                {% csrf_token %}
                <input type="submit" value="Apagar esta Questão" />
        </form>
        <br>
        <br>
        <button type="submit" form="form1" formaction="{% url 'votacao:apagaropcao' questao.id %}"><b>Apagar Opção selecionada</b></button>
    {% endif %}
    <br>
    <br>

{% endblock %}

Exercícios 4-9/sitepr/sitepr/votacao/templates/votacao/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title> {% block titulo %} Lista de perguntas {% endblock %} </title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'votacao/css/estilos.css' %}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="{% static 'votacao/scripts/scripts.js' %}"></script>
</head>
<body>
    <div>
        {% if request.user.is_authenticated %}
            <a onmouseover="show()" id="u" onmouseout="hide()">{{request.user.username}} tem a sessão iniciada</a>
        <br>
        <br>
        <center><img id="userimage" src="{{ uploaded_file_url }}" style="display:none;"></center>
    </div>
        {% else %}
            <p>O utilizador não tem a sessão iniciada</p>
            <a href="{% url 'votacao:registar' %}">Registar</a>

            <a href="{% url 'votacao:iniciarsessao' %}">Iniciar Sessão</a>
        {% endif %}
    </div>
    <br>
    {% block body %}
        <button id="botaoQuestoes" onclick="listaQuestoes()">
            Mostrar lista de Questões
        </button>
    <div id="questoes" style="display: none">
       {% if latest_question_list %}
        {% for questao in latest_question_list %}
        <ul>
            <li>
                <a href="{% url 'votacao:detalhe' questao.id %}">{{ questao.questao_texto }}
                </a><br><br>
            </li>
        </ul>
        {% endfor %}
                <a href="{% url 'votacao:view_questao_otimizada'%}">Criar nova Questão</a>
                <br><br>
    {% else %}
        <p>Não há questões disponíveis.</p>
    {% endif %}

    </div>
    <div>
        {% if request.user.is_authenticated %}
            <p><a href="{% url 'votacao:perfil' %}"/>O teu perfil</p>
        {% endif %}
    </div>
{% endblock %}

{% block homepage %}
{% endblock %}
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.0/jquery.min.js”></script>
</body>
</html>

Exercícios 4-9/sitepr/sitepr/votacao/templates/votacao/iniciarsessao.html
{% extends "./secondbase.html" %}

{% block titulo %} Iniciar Sessão {% endblock %}

{% block body %}

    <form id="form1" action="{% url 'votacao:iniciarsessao' %}" method="post">
        {% csrf_token %}
        <div>
          <h1>INICIAR SESSÃO</h1>
          <label for="username"><strong>Nome de utilizador</strong></label>
            <input type="text" placeholder="Introduzir nome de utilizador" name="username" required>
            <br><br>
            <label for="password"><strong>Palavra-passe</strong></label>
            <input type="password" placeholder="Introduzir palavra-passe" name="password" required>
            <br><br>
          </div>
          <button type="submit"><strong>INICIAR SESSÃO</strong></button>
    </form>
    <br>
    <br>

{% endblock %}

Exercícios 4-9/sitepr/sitepr/votacao/templates/votacao/novaopcao.html
{% extends "./secondbase.html" %}

{% block titulo %} Nova Opção {% endblock %}

{% block body %}

<h2>Texto da nova Opção:</h2>
    <form action="{% url 'votacao:view_opcao_otimizada' questao.id %}" method="post">
        {% csrf_token %}
        <input type="text" name="opcao" id="opcao">
        <input type="submit" value="Gravar nova Opção">
    </form>
    <br>

{% endblock %}

Exercícios 4-9/sitepr/sitepr/votacao/templates/votacao/perfil.html
{% extends "./secondbase.html" %}

{% block titulo %} Perfil {% endblock %}

{% block body %}

<div>
    {% if request.user.is_authenticated %}
        <h2>BEM-VINDO!</h2>
        <p>
            <img src="{{ uploaded_file_url }}" alt="Imagem do utilizador" onmouseover="showUserInfo()" id="u" onmouseout="hideUserInfo()">
        </p>
        <center><form id="userInfo" action="{% url 'votacao:logoutview' %}" style="display:none;">
            <label for="username">Nome de utilizador:</label>
            <input type="text" id="username" name="username" value="{{request.user.username}}" readonly>
            <br><br>
            <label for="email">E-mail:</label>
            <input type="text" id="email" name="email" value="{{request.user.email}}" readonly>
            <br><br>
            <label for="curso">Curso:</label>
            <input type="text" id="curso" name="curso" value="{{request.user.aluno.course}}" readonly>
            <br><br>
        </form>
        </center>
            <br>
            <br>
            <form method="post" enctype="multipart/form-data" action="{% url 'votacao:fazer_upload' %}">
                {% csrf_token %}
                <input type="file" name="myfile">
                <br>
                <br>
                <input type="submit" value="Upload">
            </form>
            {% if uploaded_file_url %}
                <br>
                <br>
                <p>Upload feito para:
                    <a href="{{ uploaded_file_url }}">{{ uploaded_file_url }}</a>
                </p>
                <br>
                <br>
            {% endif %}
            <input type="submit" form="userInfo" value="TERMINAR SESSÃO">
    {% endif %}
</div>
    <br>

{% endblock %}

Exercícios 4-9/sitepr/sitepr/votacao/templates/votacao/registar.html
{% extends "./secondbase.html" %}

{% block titulo %} Registo {% endblock %}

{% block body %}

<form id="form1" action="{% url 'votacao:registar'%}" method="post">
    {% csrf_token %}
    <div>
      <h1>REGISTAR</h1>
      <label for="username"><strong>Nome de utilizador</strong></label>
        <input type="text" placeholder="Introduzir nome de utilizador" name="username" required>
        <br><br>
        <label for="email"><strong>E-mail</strong></label>
        <input type="text" placeholder="Introduzir e-mail" name="email" required>
        <br><br>
        <label for="password"><strong>Palavra-passe</strong></label>
        <input type="password" placeholder="Introduzir palavra-passe" name="password" required>
        <br><br>
        <label for="course"><strong>Curso</strong></label>
        <input type="text" placeholder="Introduzir curso" name="course" required>
        <br><br>
      </div>
      <button type="submit"><strong>REGISTAR</strong></button>
</form>
   <br>
   <br>

{% endblock %}

Exercícios 4-9/sitepr/sitepr/votacao/templates/votacao/resultados.html
{% extends "./secondbase.html" %}

{% block titulo %} Resultados {% endblock %}

{% block body %}

    <h1>{{ questao.questao_texto }}</h1>
    <form action="{% url 'votacao:detalhe' questao.id %}" method="post">
        {% csrf_token %}
        <ul>
        {% for opcao in questao.opcao_set.all %}
        <li>{{ opcao.opcao_texto }} -- {{ opcao.votos }} voto{{ opcao.votos|pluralize }}</li>
        {% endfor %}
        </ul>
        <input type="submit" value="Votar novamente?"/>
    </form>
    <br>
    <br>

{% endblock %}

Exercícios 4-9/sitepr/sitepr/votacao/templates/votacao/secondbase.html
{% extends "./index.html" %}

{% block homepage %}
<form action="{% url 'votacao:index' %}">
    <button type="submit"><b>Voltar à página inicial</b></button>
</form>
<br>
<br>
{% endblock %}